---
- name: Ensure dotfiles repository is cloned locally.
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_repo_destination }}"
  become: no

- name: Ensure all configured dotfiles are links.
  shell: "ls -F {{ dotfiles_location }}/{{ item }}"
  register: existing_dotfile_info
  failed_when: false
  always_run: yes
  changed_when: false
  with_items: "{{ dotfiles_files }}"

- name: Create item as a directory for recursive directory creation
  file:
    path: "{{ dotfiles_location }}/{{ item.1.item }}"
    state: directory
  when: "'No such file or directory' in item.1.stderr"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Remove existing dotfiles file if a replacement is being linked.
  file:
    path: "{{ dotfiles_location }}/{{ dotfiles_files[item.0] }}"
    state: absent
  when: "'@' not in item.1.stdout"
  with_indexed_items: "{{ existing_dotfile_info.results }}"

- name: Link dotfiles into home folder.
  file:
    src: "{{ dotfiles_repo_destination }}/{{ item }}"
    dest: "{{ dotfiles_location }}/{{ item }}"
    state: link
  become: no
  with_items: "{{ dotfiles_files }}"
