---
- name: Assure Atom and Atom package manager (APM) are installed
  homebrew_cask: name=atom state=present

- name: Upgrade Atom packages
  atom:
    upgrade_all: yes
  when: atom_upgrade_all
  environment:
    PATH: "{{ bin_dir }}:{{ ansible_env.PATH }}"

- name: Ensure configured Atom packages are installed
  atom:
    name: "{{ item }}"
    state: present
  with_items: "{{ atom_packages }}"
  environment:
    PATH: "{{ bin_dir }}:{{ ansible_env.PATH }}"
