---
- name: tap homebrew/dupes
  homebrew_tap: tap=homebrew/dupes state=present

- name: tap homebrew/homebrew-php
  homebrew_tap: tap=homebrew/php state=present

- include: php{{php_version}}.yml

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
