---
- name: install php
  homebrew: name=php56 state=latest install_options="--with-mysql --with-apache"

- name: install php modules
  homebrew: name={{item}} state=latest
  with_items:
    - php56-apcu
    - php56-http
    - php56-xdebug
    - php56-memcached
    - php56-yaml
    - php56-imagick
    - php56-mcrypt
    - php56-intl
    - php56-pdo-pgsql

- name: activate mod_php
  become: yes
  lineinfile: >
    dest=/etc/apache2/httpd.conf
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=true
  with_items:
    - { regexp: '^#?LoadModule php5_module', line: "LoadModule php5_module    /usr/local/opt/php56/libexec/apache2/libphp5.so" }

- name: configure the php.ini settings
  lineinfile: >
    dest=/usr/local/etc/php/5.5/php.ini
    regexp="{{ item.regexp }}"
    line="{{ item.line }}"
    state=present
    create=yes
  with_items:
    - { regexp: 'max_execution_time', line: 'max_execution_time = 7200' }
    - { regexp: 'max_input_time', line: 'max_input_time = 7200' }
    - { regexp: 'memory_limit', line: 'memory_limit = -1' }
    - { regexp: 'post_max_size', line: 'post_max_size = 200M' }
    - { regexp: 'upload_max_filesize', line: 'upload_max_filesize = 200M' }
    - { regexp: 'max_file_uploads', line: 'max_file_uploads = 100' }
    - { regexp: 'date.timezone', line: 'date.timezone = Europe/Brussels' }
    - { regexp: 'date.default_latitude', line: 'date.default_latitude = 50.877369' }
    - { regexp: 'date.default_longitude', line: 'date.default_longitude = 4.684167' }
    - { regexp: 'session.cookie_httponly', line: 'session.cookie_httponly = 1' }
    - { regexp: ';?phar.readonly', line: 'phar.readonly = Off' }
