---
osx_defaults_without_domain:
  # Disable press-and-hold for keys in favor of key repeat.
  - { key: ApplePressAndHoldEnabled, type: boolean, value: false }
osx_defaults:
  - { domain: 'com.apple.dock', key: 'autohide', type: boolean, value: true }
  # Use AirDrop over every interface. srsly this should be a default.
  - { domain: com.apple.NetworkBrowser, key: BrowseAllInterfaces, type: string, value: 1 }
  # Always open everything in Finder's list view. This is important.
  - { domain: com.apple.Finder, key: FXPreferredViewStyle, type: string, value: Nlsv }
  # Set a really fast key repeat.
  - { domain: NSGlobalDomain, key: KeyRepeat, type: int, value: 2 }
  # Set the Finder prefs for showing a few different volumes on the Desktop.
  - { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
  - { domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, type: bool, value: true }
  # Run the screensaver if we're in the bottom-left hot corner.
  - { domain: com.apple.dock, key: wvous-bl-corner, type: int, value: 5 }
  - { domain: com.apple.dock, key: wvous-bl-modifier, type: int, value: 0 }
  # Hide Safari's bookmark bar.
  - { domain: com.apple.Safari, key: ShowFavoritesBar, type: bool, value: false }
  # Set up Safari for development.
  - { domain: com.apple.Safari, key: IncludeInternalDebugMenu, type: bool, value: true }
  - { domain: com.apple.Safari, key: IncludeDevelopMenu, type: bool, value: true }
  - { domain: com.apple.Safari, key: WebKitDeveloperExtrasEnabledPreferenceKey, type: bool, value: true }
  - { domain: com.apple.Safari, key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled, type: bool, value: true }
  # Enable transparency in the menu bar and elsewhere on Yosemite
  - { domain: com.apple.universalaccess, key: reduceTransparency, type: bool, value: false }
  # Disable the over-the-top focus ring animation
  - { domain: NSGlobalDomain, key: NSUseAnimatedFocusRing, type: bool, value: false }
  # Expand save panel by default
  - { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true }
  - { domain: NSGlobalDomain, key: NSNavPanelExpandedStateForSaveMode2, type: bool, value: true }
  # Expand print panel by default
  - { domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint, type: bool, value: true }
  - { domain: NSGlobalDomain, key: PMPrintingExpandedStateForPrint2, type: bool, value: true }
  # Save to disk (not to iCloud) by default
  - { domain: NSGlobalDomain, key: NSDocumentSaveNewDocumentsToCloud, type: bool, value: false }
  # Automatically quit printer app once the print jobs complete
  - { domain: com.apple.print.PrintingPrefs, key: "Quit When Finished", type: bool, value: true }
  # Disable the “Are you sure you want to open this application?” dialog
  - { domain: com.apple.LaunchServices, key: LSQuarantine, type: bool, value: false }
  # Disable Resume system-wide
  - { domain: com.apple.systempreferences, key: NSQuitAlwaysKeepsWindows, type: bool, value: false }
  # Disable automatic termination of inactive apps
  - { domain: NSGlobalDomain, key: NSDisableAutomaticTermination, type: bool, value: true }
  # Reveal IP address, hostname, OS version, etc. when clicking the clock
  # in the login window
  - { domain: com.apple.loginwindow, key: AdminHostInfo, type: string, value: HostName }
  # Disable smart quotes as they’re annoying when typing code
  - { domain: NSGlobalDomain, key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false }
  # Disable smart dashes as they’re annoying when typing code
  - { domain: NSGlobalDomain, key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false }
  # Enable full keyboard access for all controls
  # (e.g. enable Tab in modal dialogs)
  - { domain: NSGlobalDomain, key: AppleKeyboardUIMode, type: int, value: 3 }
  # Use scroll gesture with the Ctrl (^) modifier key to zoom
  - { domain: com.apple.universalaccess, key: closeViewScrollWheelToggle, type: bool, value: true }
  - { domain: com.apple.universalaccess, key: HIDScrollZoomModifierMask, type: int, value: 262144 }
  # Follow the keyboard focus while zoomed in
  - { domain: com.apple.universalaccess, key: closeViewZoomFollowsFocus, type: bool, value: true }
  # Disable auto-correct
  - { domain: NSGlobalDomain, key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false }
  # Require password immediately after sleep or screen saver begins
  - { domain: com.apple.screensaver, key: askForPassword, type: int, value: 1 }
  - { domain: com.apple.screensaver, key: askForPasswordDelay, type: float, value: 0 }
  # Save screenshots to the desktop
  - { domain: com.apple.screencapture, key: location, type: string, value: "${HOME}/Desktop" }
  # Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)
  - { domain: com.apple.screencapture, key: type, type: string, value: "png" }
  # Disable shadow in screenshots
  - { domain: com.apple.screencapture, key: disable-shadow, type: bool, value: true }
  # Enable subpixel font rendering on non-Apple LCDs
  - { domain: NSGlobalDomain, key: AppleFontSmoothing, type: int, value: 2 }
  # Enable HiDPI display modes (requires restart)
  - { domain: com.apple.windowserver, key: DisplayResolutionEnabled, type: bool, value: true }
  # Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons
  - { domain: com.apple.finder, key: QuitMenuItem, type: bool, value: true }
  # Finder: disable window animations and Get Info animations
  - { domain: com.apple.finder, key: DisableAllAnimations, type: bool, value: true }
  # Set Desktop as the default location for new Finder windows
  # For other paths, use `PfLo` and `file:///full/path/here/`
  - { domain: com.apple.finder, key: NewWindowTarget, type: string, value: "PfLo" }
  - { domain: com.apple.finder, key: NewWindowTargetPath, type: string, value: "file://${HOME}/" }
  # Show icons for hard drives, servers, and removable media on the desktop
  - { domain: com.apple.finder, key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
  - { domain: com.apple.finder, key: ShowHardDrivesOnDesktop, type: bool, value: true }
  - { domain: com.apple.finder, key: ShowMountedServersOnDesktop, type: bool, value: true }
  - { domain: com.apple.finder, key: ShowRemovableMediaOnDesktop, type: bool, value: true }
  # Finder: show hidden files by default
  #- { domain: com.apple.finder, key: AppleShowAllFiles, type: bool, value: true }
  # Finder: show all filename extensions
  - { domain: NSGlobalDomain, key: AppleShowAllExtensions, type: bool, value: true }
  # Finder: show status bar
  - { domain: com.apple.finder, key: ShowStatusBar, type: bool, value: true }
  # Finder: show path bar
  - { domain: com.apple.finder, key: ShowPathbar, type: bool, value: true }
  # Display full POSIX path as Finder window title
  - { domain: com.apple.finder, key: _FXShowPosixPathInTitle, type: bool, value: true }
  # When performing a search, search the current folder by default
  - { domain: com.apple.finder, key: FXDefaultSearchScope, type: string, value: "SCcf" }
  # Disable the warning when changing a file extension
  - { domain: com.apple.finder, key: FXEnableExtensionChangeWarning, type: bool, value: false }
  # Enable spring loading for directories
  - { domain: NSGlobalDomain, key: com.apple.springing.enabled, type: bool, value: true }
  # Remove the spring loading delay for directories
  - { domain: NSGlobalDomain, key: com.apple.springing.delay, type: float, value: 0 }
  # Avoid creating .DS_Store files on network volumes
  - { domain: com.apple.desktopservices, key: DSDontWriteNetworkStores, type: bool, value: true }
  # Disable disk image verification
  - { domain: com.apple.frameworks.diskimages, key: skip-verify, type: bool, value: true }
  - { domain: com.apple.frameworks.diskimages, key: skip-verify-locked, type: bool, value: true }
  - { domain: com.apple.frameworks.diskimages, key: skip-verify-remote, type: bool, value: true }
  # Automatically open a new Finder window when a volume is mounted
  - { domain: com.apple.frameworks.diskimages, key: auto-open-ro-root, type: bool, value: true }
  - { domain: com.apple.frameworks.diskimages, key: auto-open-rw-root, type: bool, value: true }
  - { domain: com.apple.finder, key: OpenWindowForNewRemovableDisk, type: bool, value: true }
  # Use list view in all Finder windows by default
  # Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
  - { domain: com.apple.finder, key: FXPreferredViewStyle, type: string, value: "Nlsv" }
  # Disable the warning before emptying the Trash
  - { domain: com.apple.finder, key: WarnOnEmptyTrash, type: bool, value: false }
  # Enable highlight hover effect for the grid view of a stack (Dock)
  - { domain: com.apple.dock, key: mouse-over-hilite-stack, type: bool, value: true }
  # Set the icon size of Dock items to 36 pixels
  - { domain: com.apple.dock, key: tilesize, type: int, value: 36 }
  # Change minimize/maximize window effect
  - { domain: com.apple.dock, key: mineffect, type: string, value: "scale" }
  # Minimize windows into their application’s icon
  - { domain: com.apple.dock, key: minimize-to-application, type: bool, value: true }
  # Enable spring loading for all Dock items
  - { domain: com.apple.dock, key: enable-spring-load-actions-on-all-items, type: bool, value: true }
  # Show indicator lights for open applications in the Dock
  - { domain: com.apple.dock, key: show-process-indicators, type: bool, value: true }
  # Move Dock to the left side of the screen
  - { domain: com.apple.dock, key: orientation, type: string, value: left }
  # Show only open applications in the Dock
  - { domain: com.apple.dock, key: static-only, type: bool, value: true }
  # Don’t animate opening applications from the Dock
  - { domain: com.apple.dock, key: launchanim, type: bool, value: false }
  # Speed up Mission Control animations
  - { domain: com.apple.dock, key: expose-animation-duration, type: float, value: 0.1 }
  # Don’t group windows by application in Mission Control
  # (i.e. use the old Exposé behavior instead)
  - { domain: com.apple.dock, key: expose-group-by-app, type: bool, value: false }
  # Disable Dashboard
  - { domain: com.apple.dashboard, key: mcx-disabled, type: bool, value: true }
  # Don’t show Dashboard as a Space
  - { domain: com.apple.dock, key: dashboard-in-overlay, type: bool, value: true }
  # Don’t automatically rearrange Spaces based on most recent use
  - { domain: com.apple.dock, key: mru-spaces, type: bool, value: false }
  # Remove the auto-hiding Dock delay
  - { domain: com.apple.dock, key: autohide-delay, type: float, value: 2 }
  # Remove the animation when hiding/showing the Dock
  - { domain: com.apple.dock, key: autohide-time-modifier, type: float, value: 0 }
  # Automatically hide and show the Dock
  - { domain: com.apple.dock, key: autohide, type: bool, value: true }
  # Make Dock icons of hidden applications translucent
  - { domain: com.apple.dock, key: showhidden, type: bool, value: true }
  # Hot corners
  # Possible values:
  #  0: no-op
  #  2: Mission Control
  #  3: Show application windows
  #  4: Desktop
  #  5: Start screen saver
  #  6: Disable screen saver
  #  7: Dashboard
  # 10: Put display to sleep
  # 11: Launchpad
  # 12: Notification Center
  # Top left screen corner → Mission Control
  - { domain: com.apple.dock, key: wvous-tl-corner, type: int, value: 2 }
  - { domain: com.apple.dock, key: wvous-tl-modifier, type: int, value: 0 }
  # Top right screen corner → Desktop
  - { domain: com.apple.dock, key: wvous-tr-corner, type: int, value: 4 }
  - { domain: com.apple.dock, key: wvous-tr-modifier, type: int, value: 0 }
  # Bottom left screen corner → Start screen saver
  - { domain: com.apple.dock, key: wvous-bl-corner, type: int, value: 5 }
  - { domain: com.apple.dock, key: wvous-bl-modifier, type: int, value: 0 }
  # Privacy: don’t send search queries to Apple
  - { domain: com.apple.Safari, key: UniversalSearchEnabled, type: bool, value: false }
  - { domain: com.apple.Safari, key: SuppressSearchSuggestions, type: bool, value: true }
  # Press Tab to highlight each item on a web page
  - { domain: com.apple.Safari, key: WebKitTabToLinksPreferenceKey, type: bool, value: true }
  - { domain: com.apple.Safari, key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2TabsToLinks, type: bool, value: true }
  # Show the full URL in the address bar (note: this still hides the scheme)
  - { domain: com.apple.Safari, key: ShowFullURLInSmartSearchField, type: bool, value: true }
  # Set Safari’s home page to `about:blank` for faster loading
  - { domain: com.apple.Safari, key: HomePage, type: string, value: "about:blank" }
  # Prevent Safari from opening ‘safe’ files automatically after downloading
  - { domain: com.apple.Safari, key: AutoOpenSafeDownloads, type: bool, value: false }
  # Allow hitting the Backspace key to go to the previous page in history
  - { domain: com.apple.Safari, key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2BackspaceKeyNavigationEnabled, type: bool, value: true }
  # Hide Safari’s bookmarks bar by default
  - { domain: com.apple.Safari, key: ShowFavoritesBar, type: bool, value: false }
  # Hide Safari’s sidebar in Top Sites
  - { domain: com.apple.Safari, key: ShowSidebarInTopSites, type: bool, value: false }
  # Disable Safari’s thumbnail cache for History and Top Sites
  - { domain: com.apple.Safari, key: DebugSnapshotsUpdatePolicy, type: int, value: 2 }
  # Enable Safari’s debug menu
  - { domain: com.apple.Safari, key: IncludeInternalDebugMenu, type: bool, value: true }
  # Make Safari’s search banners default to Contains instead of Starts With
  - { domain: com.apple.Safari, key: FindOnPageMatchesWordStartsOnly, type: bool, value: false }
  # Enable the Develop menu and the Web Inspector in Safari
  - { domain: com.apple.Safari, key: IncludeDevelopMenu, type: bool, value: true }
  - { domain: com.apple.Safari, key: WebKitDeveloperExtrasEnabledPreferenceKey, type: bool, value: true }
  - { domain: com.apple.Safari, key: com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled, type: bool, value: true }
  # Add a context menu item for showing the Web Inspector in web views
  - { domain: NSGlobalDomain, key: WebKitDeveloperExtras, type: bool, value: true }
  # Copy email addresses as `foo@example.com` instead of `Foo Bar <foo@example.com>` in Mail.app
  - { domain: com.apple.mail, key: AddressesIncludeNameOnPasteboard, type: bool, value: false }
  # Disable inline attachments (just show the icons)
  - { domain: com.apple.mail, key: DisableInlineAttachmentViewing, type: bool, value: true }
  # Disable automatic spell checking
  - { domain: com.apple.mail, key: SpellCheckingBehavior, type: string, value: "NoSpellCheckingEnabled" }
  # Show the main window when launching Activity Monitor
  - { domain: com.apple.ActivityMonitor, key: OpenMainWindow, type: bool, value: true }
  # Visualize CPU usage in the Activity Monitor Dock icon
  - { domain: com.apple.ActivityMonitor, key: IconType, type: int, value: 5 }
  # Show all processes in Activity Monitor
  - { domain: com.apple.ActivityMonitor, key: ShowCategory, type: int, value: 0 }
  # Sort Activity Monitor results by CPU usage
  - { domain: com.apple.ActivityMonitor, key: SortColumn, type: string, value: "CPUUsage" }
  - { domain: com.apple.ActivityMonitor, key: SortDirection, type: int, value: 0 }
  # Use plain text mode for new TextEdit documents
  - { domain: com.apple.TextEdit, key: RichText, type: int, value: 0 }
  # Open and save files as UTF-8 in TextEdit
  - { domain: com.apple.TextEdit, key: PlainTextEncoding, type: int, value: 4 }
  - { domain: com.apple.TextEdit, key: PlainTextEncodingForWrite, type: int, value: 4 }
  # Enable the debug menu in Disk Utility
  - { domain: com.apple.DiskUtility, key: DUDebugMenuEnabled, type: bool, value: true }
  - { domain: com.apple.DiskUtility, key: advanced-image-options, type: bool, value: true }
